### ISSUE TITLE
binary example

### ISSUE THREAD

**Issue by max-mapper** [dominictarr/level-replicate#1]
hey, how do you make this do binary?

**Comment by dominictarr** [comment]
ah, just use msg-pack instead of stream serializer - I'll have to make a patch for this.

**Comment by max-mapper** [comment]
@dominictarr ok tried this, got this:

![screen shot 2013-06-18 at 4 33 19 pm](https://f.cloud.github.com/assets/39759/672092/7d681af6-d86f-11e2-811c-2666434098aa.png)

which is a result of this line:

https://github.com/dominictarr/msgpack-stream/blob/master/index.js#L53

e.g. even though you're using msgpack-stream which uses msgpack-browserify which will use a good msgpack implementation for the browser you are still using Buffers in the msgpack-stream module which uses buffer-browserify which is broken + inadequate

maybe bops is the right thing to use instead?

**Comment by dominictarr** [comment]
Ah yes - correct. If this is urgent, you are gonna need to make a pull request, gonna be on the road today/tomorrow.
then we can hack on this stuff in a cafe or something!

**Comment by max-mapper** [comment]
well, i'm getting on a plane to Boston in 12 hours but I'll be back for
nodeconf :D

Not urgent, but it would be nice to start making browser tests a "thing" in
all of these level-\* repos

**Comment by dominictarr** [comment]
totally.

**Comment by dominictarr** [comment]
fixed!

**Comment by max-mapper** [comment]
I tried to use this today, ran into msgpack errors.

after initializing a replication over a binary websocket the server receives one chunk which causes it to crash:

``` js
// from console.log(chunk):
<Buffer 00 00 00 00>

// server crash stack:

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: -1 trailing bytes
    at Object.decode (/Users/maxogden/src/js/level-replicate/node_modules/msgpack-stream/node_modules/msgpack-browserify/node_modules/msgpack-js/msgpack.js:193:47)
    at /Users/maxogden/src/js/level-replicate/node_modules/msgpack-stream/index.js:70:31
    at Stream.parse (/Users/maxogden/src/js/level-replicate/node_modules/msgpack-stream/index.js:132:21)
    at Stream.stream.write (/Users/maxogden/src/js/level-replicate/node_modules/msgpack-stream/node_modules/through/index.js:22:11)
    at Stream.method [as write] (/Users/maxogden/src/js/level-replicate/node_modules/stream-combiner/node_modules/duplexer/index.js:37:39)
    at WebsocketStream.ondata (stream.js:51:26)
    at WebsocketStream.EventEmitter.emit (events.js:117:20)
    at WebsocketStream.onMessage (/Users/maxogden/src/js/socket-sync/node_modules/websocket-stream/index.js:34:8)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.self._receiver.onbinary (/Users/maxogden/src/js/auth-socket/node_modules/ws/lib/WebSocket.js:549:10)
```

the client receives 2 chunks:

![screen shot 2013-07-21 at 3 57 32 pm](https://f.cloud.github.com/assets/39759/832461/0a251b08-f259-11e2-9ee6-f5d8d748a409.png)

no errors on the client, but it closes after the server crashes

**Comment by max-mapper** [comment]
I think a demo in one of these replication repos that showed proper usage between client and server would be awesome :D

**Comment by max-mapper** [comment]
(note, my previous comments were made after fixing https://github.com/dominictarr/msgpack-stream/pull/5, so it is still a valid bug I think)

**Comment by max-mapper** [comment]
cc @juliangruber

**Comment by juliangruber** [comment]
does it work with the json-buffer version?

**Comment by max-mapper** [comment]
Just tried with json-buffer. When I do this on both sides over a binary websocket stream:

``` js
var replicator = replicate(db, 'master', "MASTER-1")
stream.pipe(replicator.createStream({tail: true})).pipe(stream)
```

level-replicate goes crazy when I add a row to the DB (triggering the first sync) and starts making thousands of keys that look like this on both sides:

![screen shot 2013-07-22 at 10 42 35 am](https://f.cloud.github.com/assets/39759/836678/57800e42-f2f6-11e2-964d-1be8756d8e9e.png)

**Comment by max-mapper** [comment]
`db` above is a sublevel, and the key of the row I put it was `0|0|-16|4096`

**Comment by max-mapper** [comment]
here is the output of the server `stream`

```
{"MASTER-1":1374514768990}
{"key":"0|0|-16|4096","value":{"0":23,"1":0,"2":16,"3":1,"4":239,"5":1,"6":0,"7":16,"8":1,"9":239,"10":1,"11":0,"12":16,"13":1,"14":240,"15":1,"16":0,"17":16,"18":1,"19":240,"20":1,"21":0,"22":16,"23":1,"24":239,"25":1,"26":0,"27":16,"28":1,"29":240,"30":1,"31":0,"32":16,"33":1,"34":240,"35":1,"36":0,"37":16,"38":1,"39":235,"40":1,"41":0,"42":1,"43":1,"44":4,"45":0,"46":11,"47":1,"48":1,"49":0,"50":4,"51":1,"52":234,"53":1,"54":0,"55":2,"56":1,"57":4,"58":0,"59":10,"60":1,"61":2,"62":0,"63":4,"64":1,"65":233,"66":1,"67":0,"68":3,"69":1,"70":4,"71":0,"72":9,"73":1,"74":3,"75":0,"76":4,"77":1,"78":232,"79":1,"80":0,"81":4,"82":1,"83":3,"84":0,"85":9,"86":1,"87":4,"88":0,"89":3,"90":1,"91":233,"92":1,"93":0,"94":4,"95":1,"96":3,"97":0,"98":9,"99":1,"100":4,"101":0,"102":3,"103":1,"104":232,"105":1,"106":0,"107":5,"108":1,"109":3,"110":0,"111":8,"112":1,"113":5,"114":0,"115":3,"116":1,"117":13,"118":0,"119":1,"120":1,"121":15,"122":0,"123":1,"124":1,"125":15,"126":0,"127":1,"128":1,"129":15,"130":0,"131":1,"132":1,"133":15,"134":0,"135":1,"136":1,"137":15,"138":0,"139":1,"140":1,"141":15,"142":0,"143":2,"144":1,"145":121,"146":0,"147":5,"148":1,"149":3,"150":0,"151":8,"152":1,"153":5,"154":0,"155":3,"156":1,"157":13,"158":0,"159":1,"160":1,"161":15,"162":0,"163":1,"164":1,"165":15,"166":0,"167":1,"168":1,"169":15,"170":0,"171":1,"172":1,"173":15,"174":0,"175":1,"176":1,"177":15,"178":0,"179":1,"180":1,"181":138,"182":1,"183":0,"184":5,"185":1,"186":3,"187":0,"188":8,"189":1,"190":5,"191":0,"192":3,"193":1,"194":221,"195":1,"196":0,"length":197,"byteLength":197,"byteOffset":0,"buffer":{"byteLength":197}},"type":"put","id":"MASTER-1","ts":"1374514890466"}
{"key":"\"0|0|-16|4096\"","type":"del","id":"MASTER-1","ts":"1374514890506"}
{"key":"0|0|-16|4096","value":{"0":23,"1":0,"2":16,"3":1,"4":239,"5":1,"6":0,"7":16,"8":1,"9":239,"10":1,"11":0,"12":16,"13":1,"14":240,"15":1,"16":0,"17":16,"18":1,"19":240,"20":1,"21":0,"22":16,"23":1,"24":239,"25":1,"26":0,"27":16,"28":1,"29":240,"30":1,"31":0,"32":16,"33":1,"34":240,"35":1,"36":0,"37":16,"38":1,"39":235,"40":1,"41":0,"42":1,"43":1,"44":4,"45":0,"46":11,"47":1,"48":1,"49":0,"50":4,"51":1,"52":234,"53":1,"54":0,"55":2,"56":1,"57":4,"58":0,"59":10,"60":1,"61":2,"62":0,"63":4,"64":1,"65":233,"66":1,"67":0,"68":3,"69":1,"70":4,"71":0,"72":9,"73":1,"74":3,"75":0,"76":4,"77":1,"78":232,"79":1,"80":0,"81":4,"82":1,"83":3,"84":0,"85":9,"86":1,"87":4,"88":0,"89":3,"90":1,"91":233,"92":1,"93":0,"94":4,"95":1,"96":3,"97":0,"98":9,"99":1,"100":4,"101":0,"102":3,"103":1,"104":232,"105":1,"106":0,"107":5,"108":1,"109":3,"110":0,"111":8,"112":1,"113":5,"114":0,"115":3,"116":1,"117":13,"118":0,"119":1,"120":1,"121":15,"122":0,"123":1,"124":1,"125":15,"126":0,"127":1,"128":1,"129":15,"130":0,"131":1,"132":1,"133":15,"134":0,"135":1,"136":1,"137":15,"138":0,"139":1,"140":1,"141":15,"142":0,"143":2,"144":1,"145":121,"146":0,"147":5,"148":1,"149":3,"150":0,"151":8,"152":1,"153":5,"154":0,"155":3,"156":1,"157":13,"158":0,"159":1,"160":1,"161":15,"162":0,"163":1,"164":1,"165":15,"166":0,"167":1,"168":1,"169":15,"170":0,"171":1,"172":1,"173":15,"174":0,"175":1,"176":1,"177":15,"178":0,"179":1,"180":1,"181":138,"182":1,"183":0,"184":5,"185":1,"186":3,"187":0,"188":8,"189":1,"190":5,"191":0,"192":3,"193":1,"194":221,"195":1,"196":0,"length":197,"byteLength":197,"byteOffset":0,"buffer":{"byteLength":197}},"type":"put","id":"MASTER-1","ts":"1374514890511"}
{"key":"\"\\\"0|0|-16|4096\\\"\"","type":"del","id":"MASTER-1","ts":"1374514890521"}
{"key":"\"0|0|-16|4096\"","type":"del","id":"MASTER-1","ts":"1374514890524"}
{"key":"0|0|-16|4096","value":{"0":23,"1":0,"2":16,"3":1,"4":239,"5":1,"6":0,"7":16,"8":1,"9":239,"10":1,"11":0,"12":16,"13":1,"14":240,"15":1,"16":0,"17":16,"18":1,"19":240,"20":1,"21":0,"22":16,"23":1,"24":239,"25":1,"26":0,"27":16,"28":1,"29":240,"30":1,"31":0,"32":16,"33":1,"34":240,"35":1,"36":0,"37":16,"38":1,"39":235,"40":1,"41":0,"42":1,"43":1,"44":4,"45":0,"46":11,"47":1,"48":1,"49":0,"50":4,"51":1,"52":234,"53":1,"54":0,"55":2,"56":1,"57":4,"58":0,"59":10,"60":1,"61":2,"62":0,"63":4,"64":1,"65":233,"66":1,"67":0,"68":3,"69":1,"70":4,"71":0,"72":9,"73":1,"74":3,"75":0,"76":4,"77":1,"78":232,"79":1,"80":0,"81":4,"82":1,"83":3,"84":0,"85":9,"86":1,"87":4,"88":0,"89":3,"90":1,"91":233,"92":1,"93":0,"94":4,"95":1,"96":3,"97":0,"98":9,"99":1,"100":4,"101":0,"102":3,"103":1,"104":232,"105":1,"106":0,"107":5,"108":1,"109":3,"110":0,"111":8,"112":1,"113":5,"114":0,"115":3,"116":1,"117":13,"118":0,"119":1,"120":1,"121":15,"122":0,"123":1,"124":1,"125":15,"126":0,"127":1,"128":1,"129":15,"130":0,"131":1,"132":1,"133":15,"134":0,"135":1,"136":1,"137":15,"138":0,"139":1,"140":1,"141":15,"142":0,"143":2,"144":1,"145":121,"146":0,"147":5,"148":1,"149":3,"150":0,"151":8,"152":1,"153":5,"154":0,"155":3,"156":1,"157":13,"158":0,"159":1,"160":1,"161":15,"162":0,"163":1,"164":1,"165":15,"166":0,"167":1,"168":1,"169":15,"170":0,"171":1,"172":1,"173":15,"174":0,"175":1,"176":1,"177":15,"178":0,"179":1,"180":1,"181":138,"182":1,"183":0,"184":5,"185":1,"186":3,"187":0,"188":8,"189":1,"190":5,"191":0,"192":3,"193":1,"194":221,"195":1,"196":0,"length":197,"byteLength":197,"byteOffset":0,"buffer":{"byteLength":197}},"type":"put","id":"MASTER-1","ts":"1374514890535"}
{"key":"\"\\\"0|0|-16|4096\\\"\"","type":"del","id":"MASTER-1","ts":"1374514890538"}
{"key":"\"0|0|-16|4096\"","type":"del","id":"MASTER-1","ts":"1374514890543"}
// goes on forever
```

**Comment by dominictarr** [comment]
Hmm, looks like it's writing the log to the main db, which is then triggering the prehooks again.

Needless to say, this should absolutely not be happening.

If you can give me a script to reproduce this, I will fix it.
