### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by hellboy81** [dominictarr/level-replicate#21]
I cannot run tests and `example/master.js`

What fork should I use? Is this module production ready?Is there another solutions to replicate LevelDB stores?

Folowing  additional modules are installed:

```
sudo npm i level-sublevel
sudo npm i random-name
sudo npm i level-test
sudo npm i tape
```

Log for tests:

```
...@...:~/../node_modules/level-replicate$ npm test

> level-replicate@1.2.1 test /../node_modules/level-replicate
> set -e; for t in test/*.js; do node $t; done

TAP version 13
# replicates with key prefix:

/../node_modules/level-replicate/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Object  has no method 'prefix'
    at getPrefix (/../node_modules/level-replicate/inject.js:75:55)
    at Object.preHook (/../level-replicate/inject.js:102:20)
    at Object.trigger (/../node_modules/level-sublevel/hooks.js:29:21)
    at Object.apply (/../node_modules/level-sublevel/nut.js:70:18)
    at EventEmitter.emitter.put (/../node_modules/level-sublevel/shell.js:49:9)
    at Test.<anonymous> (/../node_modules/level-replicate/test/char-keys.js:17:9)
    at Test.bound [as _cb] (/../node_modules/level-replicate/node_modules/tape/lib/test.js:59:32)
    at Test.run (/../node_modules/level-replicate/node_modules/tape/lib/test.js:72:10)
    at Test.bound [as run] (/../node_modules/level-replicate/node_modules/tape/lib/test.js:59:32)
    at Object.next [as _onImmediate] (/../node_modules/level-replicate/node_modules/tape/lib/results.js:66:15)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by dominictarr** [comment]
yeah this needs to be updated to work with level-sublevel@6, it works with level-sublevel@5 though.

**Comment by hellboy81** [comment]
Can I use `level_replicate` with `multilevel` simultaneously?

**Comment by dominictarr** [comment]
@hellboy81 yes that should work - if it isn't working post your code. oh yeah, I think level-replicate needs to be updated to work with the latest level-sublevel. Also have a look at @hij1nx's level-replicator
