### ISSUE TITLE
TypeError: Object #<Stream> has no method 'end'

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/level-replicate#7]
When the level-replicate handler is in something like reconnect, e.g.:

``` js
reconnect(function (con) {
  con.pipe(master.createStream({ tail: true })).pipe(con);
}).connect('/engine');
```

when reconnecting this error is thrown:

```
TypeError: Object #<Stream> has no method 'end'
    at Stream.onend (stream.js:79:10)
    at Stream.EventEmitter.emit (events.js:117:20)
    at Stream.stream.emit (/Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/stream-serializer/index.js:59:33)
    at next (/Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-stream-to-stream/index.js:75:41)
    at next (/Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-cat/index.js:23:11)
    at /Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-cat/index.js:32:13
    at /Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-stream/throughs.js:26:22
    at /Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-stream/throughs.js:87:7
    at next (/Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-cat/index.js:23:11)
    at /Users/julian/pro/reactive-chat/node_modules/level-replicate/node_modules/pull-cat/index.js:32:13
```

**Comment by juliangruber** [comment]
oh, this is actually a problem with engine.io-stream.
